### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [NatashaPavelko/bootstrap#1]
1)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/96922105-198ad900-14b8-11eb-9785-a8c565aef59c.png)

**Comment by NatashaPavelko** [comment]
Исправлено валидность кода.


https://github.com/NatashaPavelko/bootstrap

https://natashapavelko.github.io/bootstrap/

чт, 22 окт. 2020 г. в 22:45, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
отлично, работа принята

пт, 23 жовт. 2020 о 09:10 NatashaPavelko <notifications@github.com> пише:
